"""ajusta tamaño campo contraseña

Revision ID: 422d45af1835
Revises: e9feb63a3032
Create Date: 2024-10-23 00:45:20.461749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422d45af1835'
down_revision = 'e9feb63a3032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
