"""edicion de atributo other_objective a nullable=true

Revision ID: 4386de24ce98
Revises: 8d42d2540e7c
Create Date: 2024-10-23 14:56:47.746768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4386de24ce98'
down_revision = '8d42d2540e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_objective', schema=None) as batch_op:
        batch_op.alter_column('other_objetive',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_objective', schema=None) as batch_op:
        batch_op.alter_column('other_objetive',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
