"""elimninar relacion user con objetivo

Revision ID: 849afe3eb06a
Revises: 422d45af1835
Create Date: 2024-10-23 13:14:45.792599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849afe3eb06a'
down_revision = '422d45af1835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_objective', schema=None) as batch_op:
        batch_op.drop_constraint('health_objective_user_id_key', type_='unique')
        batch_op.drop_constraint('health_objective_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_objective', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('health_objective_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_unique_constraint('health_objective_user_id_key', ['user_id'])

    # ### end Alembic commands ###
