"""cambio de atributo en helthobjetive : descripction a other_objective

Revision ID: 8af93c507c40
Revises: b8997d42bdd4
Create Date: 2024-10-23 13:49:31.762447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af93c507c40'
down_revision = 'b8997d42bdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_objective', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_objetive', sa.String(length=255), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_objective', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('other_objetive')

    # ### end Alembic commands ###
