"""añadir atributo: health_restrictiona healt_profile

Revision ID: b8997d42bdd4
Revises: ea5797488d49
Create Date: 2024-10-23 13:29:42.186619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8997d42bdd4'
down_revision = 'ea5797488d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profile', schema=None) as batch_op:
        batch_op.alter_column('health_restrictions',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profile', schema=None) as batch_op:
        batch_op.alter_column('health_restrictions',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
