"""añadir atributo: health_restrictions  a healt_profile

Revision ID: ea5797488d49
Revises: 849afe3eb06a
Create Date: 2024-10-23 13:25:10.113742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5797488d49'
down_revision = '849afe3eb06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_restrictions', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profile', schema=None) as batch_op:
        batch_op.drop_column('health_restrictions')

    # ### end Alembic commands ###
